// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMeCBbAfYZLTa5Z_PoABhmgs4x9Bg6bGA',
    appId: '1:506391747906:web:ae76750fbc4ed445ccbcdb',
    messagingSenderId: '506391747906',
    projectId: 'jar-talk',
    authDomain: 'jar-talk.firebaseapp.com',
    storageBucket: 'jar-talk.firebasestorage.app',
    measurementId: 'G-J4KBFWF34Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIePWzgh5GarOfoPTNWwn6V0tnOd30Wr0',
    appId: '1:506391747906:android:0a45c33583b1ebecccbcdb',
    messagingSenderId: '506391747906',
    projectId: 'jar-talk',
    storageBucket: 'jar-talk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5FCmxBQWHzG7pAMcQB54wPLkHRT7ylRE',
    appId: '1:506391747906:ios:091b7ceabd9ddb3eccbcdb',
    messagingSenderId: '506391747906',
    projectId: 'jar-talk',
    storageBucket: 'jar-talk.firebasestorage.app',
    iosBundleId: 'com.example.jarTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5FCmxBQWHzG7pAMcQB54wPLkHRT7ylRE',
    appId: '1:506391747906:ios:091b7ceabd9ddb3eccbcdb',
    messagingSenderId: '506391747906',
    projectId: 'jar-talk',
    storageBucket: 'jar-talk.firebasestorage.app',
    iosBundleId: 'com.example.jarTalk',
  );
}
